version: '3.1'

services:

  mongo:
    image: mongo:6.0.2
    ports:
      - '27017:27017'
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s4ndw1chr3c1p3RUS7
      MONGO_INITDB_DATABASE: sandwich-recipes
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
